Complete the requirements section of the report
apeinot/incubator-nemo pull request #15
Opened 2019-02-25 12:01 UTC by apeinot

Describe the requirement of the function that will be impacted by the refactoring.
We try to stick to the standard for describing the functional requirements.
This should resolve #3

2019-02-25 12:29 UTC, Samuelhertzberg requested changes
"| Requirement Description         | The method *identified* edges with output tag and fetches their Next Intra Task Operator Info " => identifies (?)

There also some inconsistency about capital letters. Sometimes there are several in a sentence such as "Very High" and some single word fields are not capitalizedd such as "prepare" and "contructor"

2019-02-25 12:44 UTC, emilelm96 requested changes
I think you should proof-read this once more, since there are some typos and grammatical errors.

2019-02-25 14:16 UTC, Samuelhertzberg approved these changes

2019-02-26 11:56 UTC, emilelm96 approved these changes

2019-02-26 11:56 UTC, merged