[NEMO-253] Refactor getInternal(Main/Additional)Output
apeinot/incubator-nemo pull request #18
Opened 2019-02-25 12:51 UTC by apeinot

Merge the two methods into one which return one map where the OutputTag for the edge without outputTag is set to main
This resolve #4

2019-02-25 13:38 UTC, Samuelhertzberg requested changes
Add explanation of the special marker. Such as:

"If a Internal Output does not have a tag it is assigned a special tag 'main'. This way all Internal Output without tags are collected as a list in the Map with the key 'main'"

2019-02-25 14:13 UTC, Samuelhertzberg approved these changes

2019-02-25 14:22 UTC, emilelm96 commented on runtime/executor/src/main/java/org/apache/nemo/runtime/executor/task/TaskExecutor.java
> +      if (internalmainOutputs != null) {
Couldn't we change this if statement to a ternary operator? Also, is it good practice to create a temporary variable like that with such a similar name, i.e. internalMainOutputs to internalmainOutputs?

2019-02-26 12:07 UTC, Jonagoo approved these changes

2019-02-26 12:07 UTC, emilelm96 approved these changes

2019-02-26 12:21 UTC, francislaus approved these changes
Nice refactoring!

2019-02-26 12:29 UTC, merged