Added discussion regarding the refactoring
apeinot/incubator-nemo pull request #20
Opened 2019-02-25 13:34 UTC by Samuelhertzberg

Added pros, cons and summary to illustrate and discuss the refactoring made, should resolve #5

2019-02-25 13:52 UTC, Jonagoo approved these changes

2019-02-25 13:56 UTC, apeinot approved these changes

2019-02-25 14:20 UTC, emilelm96 approved these changes

2019-02-25 15:54 UTC, francislaus requested changes
I really like your text - it is well written.

But I think that 'Benefits' should start with a lowercase character.

2019-02-26 12:05 UTC, emilelm96 approved these changes

2019-02-26 12:35 UTC, francislaus approved these changes
Nice!

2019-02-26 12:36 UTC, merged