Analyzed the tests for the class TaskExecutor
apeinot/incubator-nemo pull request #21
Opened 2019-02-25 13:38 UTC by francislaus

This answered the following questions:

* What are the tests?
* Do the tests cover the requirements?
* Does your refactoring introduce anything that requires more tests?

This should close #11

2019-02-25 13:44 UTC, apeinot requested changes
In the last paragraph, the two first sentences are contradictory. To be fix

2019-02-25 14:12 UTC, Samuelhertzberg requested changes
"Therefore, we do not need to add extra test cases." To be removed
"6/7" => "six out of seven"

2019-02-26 07:03 UTC, francislaus commented
Made changes accordingly to the comments. I was not quite sure about the comments by @apeinot, I hope I did what you requested

2019-02-26 07:26 UTC, emilelm96 approved these changes

2019-02-26 09:23 UTC, apeinot approved these changes

2019-02-26 12:24 UTC, Samuelhertzberg approved these changes

2019-02-26 13:07 UTC, emilelm96 reviewed
NullPointerException should be spelled with a big N.

2019-02-26 13:07 UTC, Jonagoo requested changes

2019-02-26 13:07 UTC, Jonagoo commented on report.md
> +One new test was added. The input data to the getTaskExecutor() function is set to entirely `null`. This should result in a nullPointerException, which the new test catch. If no nullPointerException
catches*

2019-02-26 13:08 UTC, francislaus commented on report.md
> +One new test was added. The input data to the getTaskExecutor() function is set to entirely `null`. This should result in a nullPointerException, which the new test catch. If no nullPointerException
*NullPointerException

2019-02-26 13:22 UTC, emilelm96 approved these changes

2019-02-26 13:24 UTC, Jonagoo approved these changes

2019-02-26 13:25 UTC, merged