Added lessons learned
apeinot/incubator-nemo pull request #23
Opened 2019-02-25 14:14 UTC by emilelmarsson

Discussed what we've learned during this project.

This should resolve #6.

2019-02-25 14:20 UTC, apeinot requested changes
Update the beggining : "Our changes does not imply the whole project, but..."
Add something about the benefits of following a clear methodology (requirements, analysis) to dive well into this type of task

2019-02-25 14:22 UTC, Samuelhertzberg requested changes
"- We gained greater understanding of the project and furthered our teamwork by going through the code together and discussing how we would refactor the code together before we began." : *together* is written twice in same sentence.

Remove UML bullet.

Change the writing bullet to something like:
"We practiced our writing as this assignment was report heavy. In addition it was interesting writing about code in this manner"

Otherwise great!

2019-02-25 20:10 UTC, Jonagoo approved these changes

2019-02-26 07:06 UTC, francislaus approved these changes
Well done!

2019-02-26 09:21 UTC, apeinot approved these changes

2019-02-26 12:25 UTC, Samuelhertzberg approved these changes

2019-02-26 12:28 UTC, merged